[package]
name = "replace_template"
version = "0.1.0"
authors = ["fuziki <hymne.shannon.projects@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
